function initializeSheets(): void {
  for (const [name, headers] of Object.entries(SHEET_HEADERS)) {
    getOrCreateSheet(name, headers);
    logInfo('initializeSheets', `Sheet "${name}" ready`);
  }

  seedDefaultWatchlist();
  seedStockUniverse();
  logInfo('initializeSheets', 'All sheets initialized');
}

function seedDefaultWatchlist(): void {
  const existing = getConfigValue('WATCHLIST');
  if (existing) return;

  const defaultWatchlist = [
    'AAPL', 'MSFT', 'GOOGL', 'AMZN', 'NVDA',
    'META', 'TSLA', 'TSM', 'AVGO', 'JPM',
    'V', 'UNH', 'MA', 'HD', 'COST',
    'NFLX', 'CRM', 'AMD', 'QCOM', 'ADBE',
  ];
  setConfigValue('WATCHLIST', JSON.stringify(defaultWatchlist));
  logInfo('seedDefaultWatchlist', `Seeded ${defaultWatchlist.length} tickers`);
}

function seedStockUniverse(): void {
  const existing = getAllTickers();
  if (existing.length > 0) return;

  // S&P 500 representative subset — expand as needed
  const tickers: string[][] = [
    ['AAPL', 'NASDAQ', 'Apple Inc.'],
    ['MSFT', 'NASDAQ', 'Microsoft Corp.'],
    ['GOOGL', 'NASDAQ', 'Alphabet Inc.'],
    ['AMZN', 'NASDAQ', 'Amazon.com Inc.'],
    ['NVDA', 'NASDAQ', 'NVIDIA Corp.'],
    ['META', 'NASDAQ', 'Meta Platforms Inc.'],
    ['TSLA', 'NASDAQ', 'Tesla Inc.'],
    ['TSM', 'NYSE', 'Taiwan Semiconductor'],
    ['AVGO', 'NASDAQ', 'Broadcom Inc.'],
    ['JPM', 'NYSE', 'JPMorgan Chase & Co.'],
    ['V', 'NYSE', 'Visa Inc.'],
    ['UNH', 'NYSE', 'UnitedHealth Group'],
    ['MA', 'NYSE', 'Mastercard Inc.'],
    ['HD', 'NYSE', 'Home Depot Inc.'],
    ['COST', 'NASDAQ', 'Costco Wholesale'],
    ['NFLX', 'NASDAQ', 'Netflix Inc.'],
    ['CRM', 'NYSE', 'Salesforce Inc.'],
    ['AMD', 'NASDAQ', 'Advanced Micro Devices'],
    ['QCOM', 'NASDAQ', 'Qualcomm Inc.'],
    ['ADBE', 'NASDAQ', 'Adobe Inc.'],
    ['LLY', 'NYSE', 'Eli Lilly and Co.'],
    ['PEP', 'NASDAQ', 'PepsiCo Inc.'],
    ['KO', 'NYSE', 'Coca-Cola Co.'],
    ['MRK', 'NYSE', 'Merck & Co.'],
    ['ABBV', 'NYSE', 'AbbVie Inc.'],
    ['PFE', 'NYSE', 'Pfizer Inc.'],
    ['TMO', 'NYSE', 'Thermo Fisher Scientific'],
    ['CSCO', 'NASDAQ', 'Cisco Systems'],
    ['ACN', 'NYSE', 'Accenture plc'],
    ['MCD', 'NYSE', "McDonald's Corp."],
    ['ABT', 'NYSE', 'Abbott Laboratories'],
    ['DHR', 'NYSE', 'Danaher Corp.'],
    ['TXN', 'NASDAQ', 'Texas Instruments'],
    ['NEE', 'NYSE', 'NextEra Energy'],
    ['PM', 'NYSE', 'Philip Morris Intl'],
    ['UPS', 'NYSE', 'United Parcel Service'],
    ['RTX', 'NYSE', 'RTX Corp.'],
    ['HON', 'NASDAQ', 'Honeywell Intl'],
    ['INTC', 'NASDAQ', 'Intel Corp.'],
    ['LOW', 'NYSE', 'Lowe\'s Companies'],
    ['ORCL', 'NYSE', 'Oracle Corp.'],
    ['AMAT', 'NASDAQ', 'Applied Materials'],
    ['BKNG', 'NASDAQ', 'Booking Holdings'],
    ['SBUX', 'NASDAQ', 'Starbucks Corp.'],
    ['GS', 'NYSE', 'Goldman Sachs Group'],
    ['BLK', 'NYSE', 'BlackRock Inc.'],
    ['ISRG', 'NASDAQ', 'Intuitive Surgical'],
    ['MDLZ', 'NASDAQ', 'Mondelez Intl'],
    ['GILD', 'NASDAQ', 'Gilead Sciences'],
    ['ADP', 'NASDAQ', 'ADP Inc.'],
    ['CVX', 'NYSE', 'Chevron Corp.'],
    ['XOM', 'NYSE', 'Exxon Mobil Corp.'],
    ['BA', 'NYSE', 'Boeing Co.'],
    ['CAT', 'NYSE', 'Caterpillar Inc.'],
    ['DE', 'NYSE', 'Deere & Co.'],
    ['MMM', 'NYSE', '3M Co.'],
    ['DIS', 'NYSE', 'Walt Disney Co.'],
    ['NKE', 'NYSE', 'Nike Inc.'],
    ['PYPL', 'NASDAQ', 'PayPal Holdings'],
    ['SQ', 'NYSE', 'Block Inc.'],
    ['SHOP', 'NYSE', 'Shopify Inc.'],
    ['SNOW', 'NYSE', 'Snowflake Inc.'],
    ['UBER', 'NYSE', 'Uber Technologies'],
    ['ABNB', 'NASDAQ', 'Airbnb Inc.'],
    ['COIN', 'NASDAQ', 'Coinbase Global'],
    ['PLTR', 'NASDAQ', 'Palantir Technologies'],
    ['RIVN', 'NASDAQ', 'Rivian Automotive'],
    ['SOFI', 'NASDAQ', 'SoFi Technologies'],
    ['ARM', 'NASDAQ', 'Arm Holdings'],
    ['PANW', 'NASDAQ', 'Palo Alto Networks'],
    ['CRWD', 'NASDAQ', 'CrowdStrike Holdings'],
    ['DDOG', 'NASDAQ', 'Datadog Inc.'],
    ['ZS', 'NASDAQ', 'Zscaler Inc.'],
    ['NET', 'NYSE', 'Cloudflare Inc.'],
    ['MU', 'NASDAQ', 'Micron Technology'],
    ['MRVL', 'NASDAQ', 'Marvell Technology'],
    ['LRCX', 'NASDAQ', 'Lam Research'],
    ['KLAC', 'NASDAQ', 'KLA Corp.'],
    ['SNPS', 'NASDAQ', 'Synopsys Inc.'],
    ['CDNS', 'NASDAQ', 'Cadence Design Systems'],
    ['FTNT', 'NASDAQ', 'Fortinet Inc.'],
    ['WDAY', 'NASDAQ', 'Workday Inc.'],
    ['TEAM', 'NASDAQ', 'Atlassian Corp.'],
    ['NOW', 'NYSE', 'ServiceNow Inc.'],
    ['INTU', 'NASDAQ', 'Intuit Inc.'],
    ['MELI', 'NASDAQ', 'MercadoLibre Inc.'],
    ['SE', 'NYSE', 'Sea Limited'],
    ['WMT', 'NYSE', 'Walmart Inc.'],
    ['TGT', 'NYSE', 'Target Corp.'],
    ['AMGN', 'NASDAQ', 'Amgen Inc.'],
    ['REGN', 'NASDAQ', 'Regeneron Pharmaceuticals'],
    ['VRTX', 'NASDAQ', 'Vertex Pharmaceuticals'],
    ['MRNA', 'NASDAQ', 'Moderna Inc.'],
    ['BIIB', 'NASDAQ', 'Biogen Inc.'],
    ['SYK', 'NYSE', 'Stryker Corp.'],
    ['BDX', 'NYSE', 'Becton Dickinson'],
    ['ZTS', 'NYSE', 'Zoetis Inc.'],
    ['CI', 'NYSE', 'Cigna Group'],
    ['ELV', 'NYSE', 'Elevance Health'],
    ['HUM', 'NYSE', 'Humana Inc.'],
    ['MCK', 'NYSE', 'McKesson Corp.'],
    ['SCHW', 'NYSE', 'Charles Schwab'],
    ['MS', 'NYSE', 'Morgan Stanley'],
    ['C', 'NYSE', 'Citigroup Inc.'],
    ['BAC', 'NYSE', 'Bank of America'],
    ['WFC', 'NYSE', 'Wells Fargo & Co.'],
    ['USB', 'NYSE', 'U.S. Bancorp'],
    ['PNC', 'NYSE', 'PNC Financial'],
    ['AXP', 'NYSE', 'American Express'],
    ['SPGI', 'NYSE', 'S&P Global Inc.'],
    ['ICE', 'NYSE', 'Intercontinental Exchange'],
    ['CME', 'NASDAQ', 'CME Group Inc.'],
    ['CB', 'NYSE', 'Chubb Limited'],
    ['AON', 'NYSE', 'Aon plc'],
    ['MMC', 'NYSE', 'Marsh McLennan'],
    ['PGR', 'NYSE', 'Progressive Corp.'],
    ['TRV', 'NYSE', 'Travelers Companies'],
    ['ALL', 'NYSE', 'Allstate Corp.'],
    ['DELL', 'NYSE', 'Dell Technologies'],
    ['HPQ', 'NYSE', 'HP Inc.'],
    ['IBM', 'NYSE', 'IBM Corp.'],
    ['GE', 'NYSE', 'GE Aerospace'],
    ['LMT', 'NYSE', 'Lockheed Martin'],
    ['NOC', 'NYSE', 'Northrop Grumman'],
    ['GD', 'NYSE', 'General Dynamics'],
    ['F', 'NYSE', 'Ford Motor Co.'],
    ['GM', 'NYSE', 'General Motors'],
    ['RACE', 'NYSE', 'Ferrari N.V.'],
    ['FDX', 'NYSE', 'FedEx Corp.'],
    ['DAL', 'NYSE', 'Delta Air Lines'],
    ['UAL', 'NASDAQ', 'United Airlines'],
    ['LUV', 'NYSE', 'Southwest Airlines'],
    ['MAR', 'NASDAQ', 'Marriott Intl'],
    ['HLT', 'NYSE', 'Hilton Worldwide'],
    ['DASH', 'NASDAQ', 'DoorDash Inc.'],
    ['RBLX', 'NYSE', 'Roblox Corp.'],
    ['SPOT', 'NYSE', 'Spotify Technology'],
    ['TTD', 'NASDAQ', 'The Trade Desk'],
    ['ROKU', 'NASDAQ', 'Roku Inc.'],
    ['U', 'NYSE', 'Unity Software'],
    ['SMCI', 'NASDAQ', 'Super Micro Computer'],
    ['ON', 'NASDAQ', 'ON Semiconductor'],
    ['ENPH', 'NASDAQ', 'Enphase Energy'],
    ['FSLR', 'NASDAQ', 'First Solar Inc.'],
    ['CEG', 'NASDAQ', 'Constellation Energy'],
    ['VST', 'NYSE', 'Vistra Corp.'],
    ['LNG', 'NYSE', 'Cheniere Energy'],
    ['ET', 'NYSE', 'Energy Transfer LP'],
    ['OXY', 'NYSE', 'Occidental Petroleum'],
    ['COP', 'NYSE', 'ConocoPhillips'],
    ['SLB', 'NYSE', 'SLB (Schlumberger)'],
    ['EOG', 'NYSE', 'EOG Resources'],
    ['FCX', 'NYSE', 'Freeport-McMoRan'],
    ['NEM', 'NYSE', 'Newmont Corp.'],
  ];

  appendRows(SHEET_NAMES.STOCK_UNIVERSE, tickers);
  logInfo('seedStockUniverse', `Seeded ${tickers.length} tickers`);
}

function setAPIKeys(): void {
  const props = PropertiesService.getScriptProperties();
  props.setProperties({
    [PROP_KEYS.SPREADSHEET_ID]: 'PASTE_YOUR_SPREADSHEET_ID_HERE',
    [PROP_KEYS.LINE_CHANNEL_ACCESS_TOKEN]: 'PASTE_YOUR_LINE_TOKEN_HERE',
    [PROP_KEYS.LINE_CHANNEL_SECRET]: 'PASTE_YOUR_CHANNEL_SECRET_HERE',
    [PROP_KEYS.LINE_GROUP_ID]: 'PASTE_YOUR_GROUP_ID_HERE',
    [PROP_KEYS.OPENAI_API_KEY]: 'PASTE_YOUR_OPENAI_KEY_HERE',
  });
  logInfo('setAPIKeys', 'API keys configured — update values in Script Properties editor');
}
